#!/usr/bin/env ruby

require 'bundler/setup'
require 'optparse'
require './hibarichan'

# パラメタオプションの解析
params = ARGV.getopts('', 'quiet', 'debug')
# rubocop:disable Style/GlobalVars
$quiet = params['quiet']  # true なら状況の詳細な出力は行わない
$debug = params['debug']  # true ならツイートの入力や出力を標準入出力に行う
# rubocop:enable Style/GlobalVars

# カレントディレクトリの移動
Dir.chdir(File.dirname(File.expand_path(__FILE__)))

# hibarichanのインスタンス作成
hibarichan = Hibarichan::Hibarichan.new('settings.yaml')

# run
hibarichan.run
